version: '3'
services:
  dev:
    image: meganetaaan/moddable-esp32-nodejs
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - ../:/workspace:cached
    environment:
      - DISPLAY
    command: /bin/sh -c "while sleep 1000; do :; done"
